<a href="https://colab.research.google.com/github/ergonrizky26/learning-data-science/blob/main/python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## FUNGSI

**Fungsi** adalah kode yang digunakan untuk menjalankan suatu aksi
Contoh fungsi adalah **print()** yang digunakan untuk menampilkan argumen pada output

In [ ]:
print('Ergon Rizky')

Ergon Rizky


In [ ]:
print('17 Maret 2025')

17 Maret 2025


In [ ]:
print(100/10)

10.0


In [ ]:
print(2*5)

10


In [ ]:
print(type(100/10))

<class 'float'>


In [ ]:
print(len('Ergon Rizky'))

11


## VARIABEL

**Variabel** adalah container yang dipakai untuk menyimpan data. Variabel dipakai agar tidak perlu mengulang menuliskan data setiap akan menjalankan suatu fungsi terhadap data tersebut. Dibuat dengan menuliskan nama variabel diikutin dengan **'='**

In [ ]:
# Contoh variabel
int_a = 10;
float_a = 10.5;
string_a = 'contoh string';
boolean_a = True;

## TIPE DATA

Beberapa tipe data yang dikenal oleh **Python**:
1. Integer -> Bilangan bulat
2. Float -> Bilangan pecahan
3. String -> Teks
4. Boolean -> True/*False*

In [ ]:
# Identifikasi tipe data
print(type(int_a))
print(type(float_a))
print(type(string_a))
print(type(boolean_a))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


## LIST

**List** adalah kumpulan data yang terstruktur dengan urutan tertentu. Dibuat dengan menuliskan **'['** dan **']'** dan dipisahkan dengan **','**. Dalam list, tiap data memiliki index dengan urutan dari 0, 1, 2, dst

**Index** diperlukan untuk **subsetting** : mendidentifikasi/memanggil data dengan urutan tertentu dari list

In [ ]:
warna = ['merah', 'kuning', 'biru']
warna[1]

'kuning'

In [ ]:
warna[-1] # Indeks -1 menunjukkan data dengan urutan terakhir

'biru'

## SLICING PADA LIST

**Slicing** adalah proses memotong list dengan range indeks tertentu. Range indeks ditulis dengan **['indeks awal : 'indeks akhir']**. </br>
Indeks awal akan diikutsertakan pada output, sedangkan Indeks akhir tidak diikutsertakan pada output.

### Latihan List dan Slicing

In [ ]:
nama = 'ergon rizky'
jarak_km = 5
jarak_mil = 5 * 0.62
jarak_beda = jarak_km == jarak_mil

print(type(nama))
print(type(jarak_km))
print(type(jarak_mil))
print(type(jarak_beda))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


In [ ]:
list_a = [nama, jarak_km, jarak_mil, jarak_beda]
list_a

['ergon rizky', 5, 3.1, False]

In [ ]:
# Slice 2 data terakhir
list_a[2:]

[3.1, False]

In [ ]:
# Slice 2 data pertama
list_a[:2]

['ergon rizky', 5]

## METODE

**Metode** adalah fungsi yang dimiliki oleh objek <br>
1. Contoh metode yg dimiliki oleh objek string :
-> **upper()** <br>
-> **count()** <br>
2. Contoh metode yg dimiliki oleh objek list :    
-> **index()** <br>
-> **count()**


In [ ]:
var_string = 'Belajar python'

# upper()
print(var_string.upper())

# count()
print(var_string.count('a'))

BELAJAR PYTHON
2


In [ ]:
var_list = ['merah', 'kuning', 'hijau', 'biru']

# index()
var_list.index('kuning')

# count()
var_list.count('merah')

1

## MENGIMPOR MODUL

**Modul** adalah file berisikan kumpulan definisi dan pernyataan python
<br>
1. Modul perlu diimpor untuk mengakses definisi yang terdapat didalamnya <br>
2. Contoh modul **math** yg didalamnya terdapat definisi konstanta **pi**
<br>
3. Modul juga bisa diimpor secara selektif, dimana hanya definisi atau pernyataan tertentu yg diimpor

In [ ]:
import math
math.pi

3.141592653589793

In [ ]:
import math as mt
mt.pi

3.141592653589793

In [ ]:
from math import pi
pi

3.141592653589793

In [ ]:
# Penggunaan pi utk menghitung volume lingkaran
r = 12
vol_bola = 4/3 * pi * r ** 3
print('Volume bola adalah {} cm^3'.format(vol_bola))

Volume bola adalah 7238.229473870882 cm^3


In [ ]:
# Penggunaan sqrt utk menghitung sisi miring segitiga siku-siku
from math import sqrt

a = 3
b = 4
c = sqrt(a**2 + b**2)
print('Sisi miring segitiga siku-siku adalah {} cm'.format(c))

Sisi miring segitiga siku-siku adalah 5.0 cm


## NUMPY ARRAY

**Numpy** adalah modul pada python yg dapat membuat dan mengolah struktur data array <br>
1. Elemen array bersifat homogen (satu tipe) <br>
2. Struktur data array optimal untuk analisis numerik <br>
3. Data array dapat dibuat dari list <br>
4. Operasi aritmatik dapat dilakukan pada data array <br>

In [ ]:
import numpy as np

var_list1 = [1, 3, 5, 7]
var_array = np.array(var_list1)
var_array

array([1, 3, 5, 7])

In [ ]:
var_array + 7

array([ 8, 10, 12, 14])

In [ ]:
var_array / 6

array([0.16666667, 0.5       , 0.83333333, 1.16666667])

In [ ]:
var_list_campur = [3, 'nama', True]
var_arrray_campur = np.array(var_list_campur)
var_arrray_campur #numpy array bersifat homogen, semua list dgn tipe data berbeda akan diubah menjadi string di array

array(['3', 'nama', 'True'], dtype='<U21')

## 2D NUMPY ARRAY

1. Array dapat berbentuk 2 dimensi
2. Array 2D dibuat dengan mengkonversi list of list

In [ ]:
var_list2 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
var_array2 = np.array(var_list2)

In [ ]:
var_array2.shape # array masih 1D

(10,)

In [ ]:
# subset array 1D
var_array2[2:5]

array([3, 4, 5])

In [ ]:
# array 2D gunakan reshape
var_array_reshape = var_array2.reshape(5, 2)
var_array_reshape

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# cek dimensi array
var_array_reshape.shape

(5, 2)

In [ ]:
# subset array 2D
var_array_reshape[1:3, :2]

array([[3, 4],
       [5, 6]])

In [ ]:
# Perkalian array
var_array3 = var_array_reshape.reshape(2, 5)
var_array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
var_array_reshape

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
var_array4 = np.matmul(var_array3, var_array_reshape)
var_array4

array([[ 95, 110],
       [220, 260]])

In [ ]:
arr_1 = np.array([1, 2, 3, 4]).reshape(2, 2)
arr_2 = np.array([5, 6, 7, 8]).reshape(2, 2)
arr_3 = np.matmul(arr_1, arr_2)
arr_3

array([[19, 22],
       [43, 50]])

In [ ]:
# perkalian array juga bisa menggunakan @
arr_1 @ arr_2

array([[19, 22],
       [43, 50]])

## SUBSETTING 2D ARRAY

1. Subset pada array 2D dilakukan dengan menuliskan row dan column (dihitung dari 0, 1, 2, dst) dengan format nama_array[nomor_row,nomor_column]
2. Subset juga bisa dilakukan dgn menggunakan range row atau column (slicing)

## ANALISIS STATISTIKA DASAR PADA ARRAY

Modul **numpy** memiliki fungsi utk menjalankan analisis statistic dasar seperti **min(), max(), sum(), mean(), media()**

In [ ]:
var_array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.mean(var_array2)

np.float64(5.5)

In [ ]:
var_array2.mean()

np.float64(5.5)

In [ ]:
np.median(var_array2)

np.float64(5.5)

In [ ]:
np.min(var_array2)

np.int64(1)

In [ ]:
np.max(var_array2)

np.int64(10)

In [ ]:
np.std(var_array2)

np.float64(2.8722813232690143)

In [ ]:
np.var(var_array2)

np.float64(8.25)

In [ ]:
np.sum(var_array2)

np.int64(55)