<a href="https://colab.research.google.com/github/ergonrizky26/learning-data-science/blob/main/python_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## FUNGSI

**Fungsi** adalah kode yang digunakan untuk menjalankan suatu aksi
Contoh fungsi adalah **print()** yang digunakan untuk menampilkan argumen pada output

In [1]:
print('Ergon Rizky')

Ergon Rizky


In [2]:
print('17 Maret 2025')

17 Maret 2025


In [3]:
print(100/10)

10.0


In [4]:
print(2*5)

10


In [5]:
print(type(100/10))

<class 'float'>


In [6]:
print(len('Ergon Rizky'))

11


## VARIABEL

**Variabel** adalah container yang dipakai untuk menyimpan data. Variabel dipakai agar tidak perlu mengulang menuliskan data setiap akan menjalankan suatu fungsi terhadap data tersebut. Dibuat dengan menuliskan nama variabel diikutin dengan **'='**

In [7]:
# Contoh variabel
int_a = 10;
float_a = 10.5;
string_a = 'contoh string';
boolean_a = True;

## TIPE DATA

Beberapa tipe data yang dikenal oleh **Python**:
1. Integer -> Bilangan bulat
2. Float -> Bilangan pecahan
3. String -> Teks
4. Boolean -> True/*False*

In [8]:
# Identifikasi tipe data
print(type(int_a))
print(type(float_a))
print(type(string_a))
print(type(boolean_a))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


## LIST

**List** adalah kumpulan data yang terstruktur dengan urutan tertentu. Dibuat dengan menuliskan **'['** dan **']'** dan dipisahkan dengan **','**. Dalam list, tiap data memiliki index dengan urutan dari 0, 1, 2, dst

**Index** diperlukan untuk **subsetting** : mendidentifikasi/memanggil data dengan urutan tertentu dari list

In [9]:
warna = ['merah', 'kuning', 'biru']
warna[1]

'kuning'

In [10]:
warna[-1] # Indeks -1 menunjukkan data dengan urutan terakhir

'biru'

## SLICING PADA LIST

**Slicing** adalah proses memotong list dengan range indeks tertentu. Range indeks ditulis dengan **['indeks awal : 'indeks akhir']**. </br>
Indeks awal akan diikutsertakan pada output, sedangkan Indeks akhir tidak diikutsertakan pada output.

### Latihan List dan Slicing

In [11]:
nama = 'ergon rizky'
jarak_km = 5
jarak_mil = 5 * 0.62
jarak_beda = jarak_km == jarak_mil

print(type(nama))
print(type(jarak_km))
print(type(jarak_mil))
print(type(jarak_beda))

<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>


In [12]:
list_a = [nama, jarak_km, jarak_mil, jarak_beda]
list_a

['ergon rizky', 5, 3.1, False]

In [13]:
# Slice 2 data terakhir
list_a[2:]

[3.1, False]

In [14]:
# Slice 2 data pertama
list_a[:2]

['ergon rizky', 5]

## METODE

**Metode** adalah fungsi yang dimiliki oleh objek <br>
1. Contoh metode yg dimiliki oleh objek string :
-> **upper()** <br>
-> **count()** <br>
2. Contoh metode yg dimiliki oleh objek list :    
-> **index()** <br>
-> **count()**


In [15]:
var_string = 'Belajar python'

# upper()
print(var_string.upper())

# count()
print(var_string.count('a'))

BELAJAR PYTHON
2


In [16]:
var_list = ['merah', 'kuning', 'hijau', 'biru']

# index()
var_list.index('kuning')

# count()
var_list.count('merah')

1

## MENGIMPOR MODUL

**Modul** adalah file berisikan kumpulan definisi dan pernyataan python
<br>
1. Modul perlu diimpor untuk mengakses definisi yang terdapat didalamnya <br>
2. Contoh modul **math** yg didalamnya terdapat definisi konstanta **pi**
<br>
3. Modul juga bisa diimpor secara selektif, dimana hanya definisi atau pernyataan tertentu yg diimpor

In [17]:
import math
math.pi

3.141592653589793

In [18]:
import math as mt
mt.pi

3.141592653589793

In [19]:
from math import pi
pi

3.141592653589793

In [20]:
# Penggunaan pi utk menghitung volume lingkaran
r = 12
vol_bola = 4/3 * pi * r ** 3
print('Volume bola adalah {} cm^3'.format(vol_bola))

Volume bola adalah 7238.229473870882 cm^3


In [21]:
# Penggunaan sqrt utk menghitung sisi miring segitiga siku-siku
from math import sqrt

a = 3
b = 4
c = sqrt(a**2 + b**2)
print('Sisi miring segitiga siku-siku adalah {} cm'.format(c))

Sisi miring segitiga siku-siku adalah 5.0 cm


## NUMPY ARRAY

**Numpy** adalah modul pada python yg dapat membuat dan mengolah struktur data array <br>
1. Elemen array bersifat homogen (satu tipe) <br>
2. Struktur data array optimal untuk analisis numerik <br>
3. Data array dapat dibuat dari list <br>
4. Operasi aritmatik dapat dilakukan pada data array <br>

In [22]:
import numpy as np

var_list1 = [1, 3, 5, 7]
var_array = np.array(var_list1)
var_array

array([1, 3, 5, 7])

In [23]:
var_array + 7

array([ 8, 10, 12, 14])

In [24]:
var_array / 6

array([0.16666667, 0.5       , 0.83333333, 1.16666667])

In [25]:
var_list_campur = [3, 'nama', True]
var_arrray_campur = np.array(var_list_campur)
var_arrray_campur #numpy array bersifat homogen, semua list dgn tipe data berbeda akan diubah menjadi string di array

array(['3', 'nama', 'True'], dtype='<U21')

## 2D NUMPY ARRAY

1. Array dapat berbentuk 2 dimensi
2. Array 2D dibuat dengan mengkonversi list of list

In [26]:
var_list2 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
var_array2 = np.array(var_list2)

In [27]:
var_array2.shape # array masih 1D

(10,)

In [28]:
# subset array 1D
var_array2[2:5]

array([3, 4, 5])

In [29]:
# array 2D gunakan reshape
var_array_reshape = var_array2.reshape(5, 2)
var_array_reshape

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [30]:
# cek dimensi array
var_array_reshape.shape

(5, 2)

In [31]:
# subset array 2D
var_array_reshape[1:3, :2]

array([[3, 4],
       [5, 6]])

In [32]:
# Perkalian array
var_array3 = var_array_reshape.reshape(2, 5)
var_array3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
var_array_reshape

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [34]:
var_array4 = np.matmul(var_array3, var_array_reshape)
var_array4

array([[ 95, 110],
       [220, 260]])

In [35]:
arr_1 = np.array([1, 2, 3, 4]).reshape(2, 2)
arr_2 = np.array([5, 6, 7, 8]).reshape(2, 2)
arr_3 = np.matmul(arr_1, arr_2)
arr_3

array([[19, 22],
       [43, 50]])

In [36]:
# perkalian array juga bisa menggunakan @
arr_1 @ arr_2

array([[19, 22],
       [43, 50]])

## SUBSETTING 2D ARRAY

1. Subset pada array 2D dilakukan dengan menuliskan row dan column (dihitung dari 0, 1, 2, dst) dengan format nama_array[nomor_row,nomor_column]
2. Subset juga bisa dilakukan dgn menggunakan range row atau column (slicing)

## ANALISIS STATISTIKA DASAR PADA ARRAY

Modul **numpy** memiliki fungsi utk menjalankan analisis statistic dasar seperti **min(), max(), sum(), mean(), media()**

In [37]:
var_array2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
np.mean(var_array2)

np.float64(5.5)

In [39]:
var_array2.mean()

np.float64(5.5)

In [40]:
np.median(var_array2)

np.float64(5.5)

In [41]:
np.min(var_array2)

np.int64(1)

In [42]:
np.max(var_array2)

np.int64(10)

In [43]:
np.std(var_array2)

np.float64(2.8722813232690143)

In [44]:
np.var(var_array2)

np.float64(8.25)

In [45]:
np.sum(var_array2)

np.int64(55)

### ARRAY GENERATOR

Modul **Numpy** memiliki beberapa fungsi untuk mengenerate array <br>
**np.random.rand()** -> generate array dengan angka float 0-1 <br>
**np.random.randint()** -> generate array dengan angka integer <br>
**np.arrange** -> generate array dengan menentukan jarak antar angkanya <br>
**np.linspace** -> generate array dengan menentukan jumlah angka yang diinginkan dalam array dengan jarak yang konstan

In [48]:
# rand()
np.random .rand(10) * 100 # mengambil nilai random dari rentang 0-100 dgn jlh 10 data

array([48.05196059, 31.2483157 , 63.05458287, 99.8205797 , 78.72220106,
        0.36162311, 77.19518487, 71.75727399, 64.41686467, 80.91093075])

In [51]:
# rand()
np.random.rand(10) * 20 + 20 # mengambil nilai random dari rentang 20-40 dgn jlh data 10

array([31.92707226, 36.52084237, 20.02305562, 24.02895742, 30.3738772 ,
       26.67160505, 33.18189574, 37.33699361, 38.95130384, 35.49352477])

In [53]:
# rand()
np.random.rand(10) * 100 + 100 # mengambil nilai random dari rentang 100-200 dgn jlh data 10

array([177.34768431, 109.23373963, 185.0191124 , 179.61925832,
       197.99468603, 198.45559624, 164.02758935, 177.83293744,
       145.46672018, 101.56799415])

In [55]:
# randint()
# 10->batas bawah, 90->batas atas, 5->jlh data
np.random.randint(10, 90, 5)

array([73, 16, 52, 54, 47])

In [62]:
# arange()
# 0->batas bawah, 100->batas atas, 2->interval/jarak antar data
np.arange(0, 102, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [64]:
# linspace()
# 0->batas bawah, 100->batas atas, 51->banyak data
np.linspace(0, 100, 51)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
        44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
        66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
        88.,  90.,  92.,  94.,  96.,  98., 100.])

In [67]:
(np.arange(0, 102, 2) == np.linspace(0, 100, 51))

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [68]:
(np.arange(0, 102, 2) == np.linspace(0, 100, 51)).all()

np.True_

In [71]:
import numpy as np

a = [0, 1, 2, 3]
b = [2, 0, 9, 2]

# Buat 2D array "c" dari 2 list tsb
c = np.array([a, b])
c

array([[0, 1, 2, 3],
       [2, 0, 9, 2]])

In [72]:
# Subset data pada posisi row 1 dan kolom 3 dari array yg dibuat
subset_c = c[1, 3]
subset_c

np.int64(2)

In [76]:
# Menentukan nilai mean dan median dari nilai yg ada di array
# mean
mean_c = np.mean(c)
mean_c

np.float64(2.375)

In [77]:
# median
median_c = np.median(c)
median_c

np.float64(2.0)

In [78]:
# convert array 2D to 1D
c.flatten()

array([0, 1, 2, 3, 2, 0, 9, 2])

In [80]:
# Generate array berisi 10 float dgn range 1250-1500
arr_float = np.random.rand(10) * 250 + 1250
arr_float

array([1357.39244221, 1340.46847736, 1282.94562151, 1387.25354294,
       1399.17065279, 1345.27919087, 1252.63623588, 1376.23697196,
       1328.31826947, 1265.65378212])

In [92]:
# Generate array berisi 10 integer dgn range 0-10
arr_int = np.random.randint(0, 10, 10)
arr_int

array([5, 9, 9, 4, 1, 4, 8, 2, 4, 5])

In [93]:
# Generate array berisi angka dgn range 0-10 dgn jarak antar angkanya 2
arr_arange = np.arange(0, 10, 2)
arr_arange

array([0, 2, 4, 6, 8])

In [89]:
# Generate array berisi 5 angka dgn range 0-10 dgn jarak antar angka yg tetap
arr_linspace = np.linspace(0, 10, 5)
arr_linspace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])